### ISSUE TITLE
Overexposed HDR

### ISSUE THREAD

**Issue by Ivan876l678** [awxkee/avif-coder#25]
Hello!
I'm trying to use this library to display hdr avif.
You did a great job!
Unfortunately, many HDR images show strong overexposure
![Screenshot_20240617_073313](https://github.com/awxkee/avif-coder/assets/9846108/f0570e46-e6c5-4b8b-a557-8cfe66ff1037)

Taken from https://www.wide-gamut.com/test/image-hdr

Direct link to AVIF
https://www.wide-gamut.com/assets/hdr/WideGamut-Neon-DisplayP3-HDR.avif

Is it possible to fix this?

**Comment by Ivan876l678** [comment]
Devices: Pixel 7 emulator (screenshot)
Samsung S23 Ultra, A72 - same results

**Comment by awxkee** [comment]
Hi. Did you use logarithmic tone mapper in constructor parameters? If so, change it to rec2408. Overexposure is known feature of global logarithmic tone mapping

**Comment by Ivan876l678** [comment]
![Screenshot_20240617_130230](https://github.com/awxkee/avif-coder/assets/9846108/43937650-447c-49f1-9f2d-dc65cdaa731d)
Yes. This is rec2408 setting. Still overexposed. 
The colors are also distorted in comparison with both the original and what Chrome shows

**Comment by awxkee** [comment]
Sorry about that however it's the best that I can do at the moment.
In the most of cases it's highly inlikely that you'll see the same results as in chrome due to chrome will use probably your HDR display instead of tonemapping. The library is intented to do always tone mapping because API of using HDR display is not documented in android ( and probably not everywhere available ) and available only on API 31+.
If you'll disable HDR in chrome results will be almost the same because Chrome will start do tone mapping also.
There is the results of mine tone mapping and MacOS and results are same.

<img width="1337" alt="Screenshot 2024-06-17 at 08 29 53" src="https://github.com/awxkee/avif-coder/assets/17083179/40b16061-3a3a-4a78-8a84-c34abdf9ce7e">

If that is important for you, then you have to reconfigure with undocumented colorspace api library by yourself because I'm not relly curious with using unstable and unclear in use API.
https://developer.android.com/ndk/reference/group/a-data-space
This API crashes some times with surprising crashes and available only for 30+.
If you'll turn off tone mapping and configure Display P3 surface with PQ Transfer function you will get the best result that you may get on your device if your display supports HDR.

**Comment by awxkee** [comment]
Or, as an alternative you may setup OpenGL/Vulkan Surface and render clear data into it. That is only two ways to achieve closest to Chrome results.

**Comment by awxkee** [comment]
There was some [discussion](https://github.com/awxkee/avif-coder/discussions/24) where I tried to explain how to get clear data for OpenGL.

**Comment by Ivan876l678** [comment]
Thank you for your time and information.
It’s a pity that, in fact, there is no api for controlling brightness in Android.
However, you have done a good job with good results.
Thank you!

**Comment by awxkee** [comment]
This is not actual `brightness` it is about physical ability of display to display colors with highest intensity :) 
Android introduces only from Android 13 [built-in solution](https://source.android.com/docs/core/display/tone-mapping) for device vendors to start implementing integrated tone mapping, because at the moment they can just skip this step ( especially for low value devices ). Probably in future 10 years they will implement and stabilize API and it will become at least usable.
At the moment sadly there are no easy options to display real HDR.
